<?php $product = Mage::registry('current_product');?>
<?php if ((string)$this->getAppId() != ''): ?>
<meta property='fb:app_id' content='<?php echo (string)$this->getAppId(); ?>'/>
<?php endif;?>
<?php if ((string)$this->getAdminId() != ''): ?>
<meta property='fb:admins' content='<?php echo (string)$this->getAdminId(); ?>' />
<?php endif;?>
<meta property='og:url' content='<?php echo $product->getProductUrl();?>'/>
<meta property='og:type' content='product'/>
<meta property='og:title' content='<?php echo trim(strip_tags(str_replace("'", "", $product->getName()))); ?>'/>
<meta property='og:description' content='<?php echo trim(strip_tags(str_replace("'", "", $product->getShortDescription()))); ?>'>
<?php foreach ($product->getMediaGallery('images') as $_image): ?>
<meta property='og:image' content='<?php echo Mage::helper('catalog/image')->init($product, 'image', $_image['file']);?>'/>
<?php endforeach;?>