<div class="homepage">
	
	
	<script src="<?php echo $this->getSkinUrl('js/') ?>glider.js" type="text/javascript"></script>
	<script type="text/javascript" charset="utf-8">
		var my_glider = new Glider('slider', {duration:0.5, autoGlide: true, frequency: 4, initialSection: 'section1'});
	</script>
	
	<div class="home-box1">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pt001-home-box1')->toHtml() ?>
	</div>
	<div class="home-box2">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pt001-home-box2')->toHtml() ?>
	</div>
	<div class="home-box3">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pt001-home-box3')->toHtml() ?>
	</div>
	<div class="clearer"></div>

</div>